/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyectooo;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author AdminColeexz
 */
public class MENUSWING extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form MENUSWING
     */
    private Player player;
    static int numerojugadores = 4;
    static String colorequipopropio = "azul";
    static int c = 0;

    public MENUSWING() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        pack();

        System.out.println(numerojugadores);

        TITULO.setText("BIENVENIDO AL MENU PRINCIPAL: " + LOGIN.JUGADORACTUAL.getUser());

        REPORTESPANEL.hide();
        CONFIGPANEL.hide();

        CANTIDADJUGADORES.setSelectedItem("4");
        CANTIDADJUGADORES.removeAllItems();
        COLOREQUIPO.removeAllItems();
        COLORPROPIO.removeAllItems();

        CANTIDADJUGADORES.addItem("2");
        CANTIDADJUGADORES.addItem("3");
        CANTIDADJUGADORES.addItem("4");
        CANTIDADJUGADORES.addItem("6");
        CANTIDADJUGADORES.addItem("8");

        COLOREQUIPO.addItem("rojo");
        COLOREQUIPO.addItem("azul");
        COLOREQUIPO.addItem("verde");
        COLOREQUIPO.addItem("amarillo");

        COLORPROPIO.addItem("rojo");
        COLORPROPIO.addItem("azul");
        COLORPROPIO.addItem("verde");
        COLORPROPIO.addItem("amarillo");

        AgregarAcciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        REPORTESPANEL = new javax.swing.JPanel();
        VOLVERREPORTES = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        CONFIGPANEL = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CANTIDADJUGADORES = new javax.swing.JComboBox<>();
        COLORPROPIO = new javax.swing.JComboBox<>();
        COLOREQUIPO = new javax.swing.JComboBox<>();
        VOLVERCONFIG = new javax.swing.JButton();
        PRINCIPAL = new javax.swing.JPanel();
        JUGAR = new javax.swing.JButton();
        TITULO = new javax.swing.JLabel();
        CONFIG = new javax.swing.JButton();
        REPORTES = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VOLVERREPORTES.setText("VOLVER");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("BIENVENIDO AL MENU DE REPORTES");

        javax.swing.GroupLayout REPORTESPANELLayout = new javax.swing.GroupLayout(REPORTESPANEL);
        REPORTESPANEL.setLayout(REPORTESPANELLayout);
        REPORTESPANELLayout.setHorizontalGroup(
            REPORTESPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REPORTESPANELLayout.createSequentialGroup()
                .addGroup(REPORTESPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REPORTESPANELLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VOLVERREPORTES))
                    .addGroup(REPORTESPANELLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REPORTESPANELLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(92, 92, 92))
        );
        REPORTESPANELLayout.setVerticalGroup(
            REPORTESPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REPORTESPANELLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VOLVERREPORTES, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setText("BIENVENIDO AL MENU DE REPORTES");

        CANTIDADJUGADORES.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        COLORPROPIO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        COLOREQUIPO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        VOLVERCONFIG.setText("VOLVER");

        javax.swing.GroupLayout CONFIGPANELLayout = new javax.swing.GroupLayout(CONFIGPANEL);
        CONFIGPANEL.setLayout(CONFIGPANELLayout);
        CONFIGPANELLayout.setHorizontalGroup(
            CONFIGPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONFIGPANELLayout.createSequentialGroup()
                .addGroup(CONFIGPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CONFIGPANELLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1))
                    .addGroup(CONFIGPANELLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(CONFIGPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(COLORPROPIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(COLOREQUIPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CONFIGPANELLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(CONFIGPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CONFIGPANELLayout.createSequentialGroup()
                        .addComponent(VOLVERCONFIG)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CONFIGPANELLayout.createSequentialGroup()
                        .addComponent(CANTIDADJUGADORES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))))
        );
        CONFIGPANELLayout.setVerticalGroup(
            CONFIGPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONFIGPANELLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(COLORPROPIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(COLOREQUIPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(CANTIDADJUGADORES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(VOLVERCONFIG)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        JUGAR.setText("Jugar");

        CONFIG.setText("Configuracion");
        CONFIG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONFIGActionPerformed(evt);
            }
        });

        REPORTES.setText("Reportes");

        SALIR.setText("Salir");

        javax.swing.GroupLayout PRINCIPALLayout = new javax.swing.GroupLayout(PRINCIPAL);
        PRINCIPAL.setLayout(PRINCIPALLayout);
        PRINCIPALLayout.setHorizontalGroup(
            PRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PRINCIPALLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(PRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JUGAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CONFIG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(REPORTES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SALIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PRINCIPALLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        PRINCIPALLayout.setVerticalGroup(
            PRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PRINCIPALLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JUGAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CONFIG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(REPORTES)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SALIR)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(REPORTESPANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CONFIGPANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PRINCIPAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(REPORTESPANEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CONFIGPANEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PRINCIPAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CONFIGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONFIGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CONFIGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENUSWING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENUSWING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENUSWING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENUSWING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENUSWING().setVisible(true);
            }
        });
    }

    public void AgregarAcciones() {
        CONFIG.addActionListener(this);
        VOLVERCONFIG.addActionListener(this);
        JUGAR.addActionListener(this);
        REPORTES.addActionListener(this);
        SALIR.addActionListener(this);
        VOLVERREPORTES.addActionListener(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CANTIDADJUGADORES;
    private javax.swing.JComboBox<String> COLOREQUIPO;
    private javax.swing.JComboBox<String> COLORPROPIO;
    private javax.swing.JButton CONFIG;
    private javax.swing.JPanel CONFIGPANEL;
    private javax.swing.JButton JUGAR;
    private javax.swing.JPanel PRINCIPAL;
    private javax.swing.JButton REPORTES;
    private javax.swing.JPanel REPORTESPANEL;
    private javax.swing.JButton SALIR;
    private javax.swing.JLabel TITULO;
    private javax.swing.JButton VOLVERCONFIG;
    private javax.swing.JButton VOLVERREPORTES;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == JUGAR) {
            if (c > 0) {
                if (numerojugadores <= Player.users.size()) {
                    ATABLEROCOLE.players.add(LOGIN.JUGADORACTUAL);
                    SELECCIONARJUGADORES sele = new SELECCIONARJUGADORES(player);
                    sele.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "el numero de jugadores seleccionados : " + numerojugadores + "\nes mayor a los jugadores\nregistrados : " + Player.users.size());
                }
            } else {
                JOptionPane.showMessageDialog(this,"debe de escoger sus colores de fichas");
            }
        } else if (e.getSource() == CONFIG) {
            c++;
            CONFIGPANEL.show();
            PRINCIPAL.hide();
        } else if (e.getSource() == REPORTES) {
            REPORTESPANEL.show();
            PRINCIPAL.hide();
        } else if (e.getSource() == SALIR) {
            LOGIN login;
            try {
                login = new LOGIN();
                login.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(MENUSWING.class.getName()).log(Level.SEVERE, null, ex);
            }

            this.dispose();
        } else if (e.getSource() == VOLVERCONFIG) {
            numerojugadores = Integer.parseInt(CANTIDADJUGADORES.getSelectedItem().toString());
            LOGIN.JUGADORACTUAL.setColor(COLORPROPIO.getSelectedItem().toString());
            colorequipopropio = COLOREQUIPO.getSelectedItem().toString();
            CONFIGPANEL.hide();
            PRINCIPAL.show();
        }
    }
}
