/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Nuestro;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author AdminColeexz
 */
public class TABLERO extends javax.swing.JFrame {

    /**
     * Creates new form TABLERO
     */
    public TABLERO() {
        initComponents();
        pack();
        setLocationRelativeTo(null);
        setResizable(false);
        jLayeredPane5.setVisible(true);
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane5 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        TABLERO = new javax.swing.JLayeredPane();
        boton01 = new javax.swing.JButton();
        boton00 = new javax.swing.JButton();
        boton02 = new javax.swing.JButton();
        boton04 = new javax.swing.JButton();
        boton03 = new javax.swing.JButton();
        boton05 = new javax.swing.JButton();
        boton06 = new javax.swing.JButton();
        boton07 = new javax.swing.JButton();
        boton08 = new javax.swing.JButton();
        boton09 = new javax.swing.JButton();
        boton10 = new javax.swing.JButton();
        boton11 = new javax.swing.JButton();
        boton12 = new javax.swing.JButton();
        boton13 = new javax.swing.JButton();
        boton14 = new javax.swing.JButton();
        boton15 = new javax.swing.JButton();
        boton16 = new javax.swing.JButton();
        boton17 = new javax.swing.JButton();
        boton18 = new javax.swing.JButton();
        boton19 = new javax.swing.JButton();
        boton20 = new javax.swing.JButton();
        boton21 = new javax.swing.JButton();
        boton22 = new javax.swing.JButton();
        boton23 = new javax.swing.JButton();
        boton24 = new javax.swing.JButton();
        boton25 = new javax.swing.JButton();
        boton26 = new javax.swing.JButton();
        boton27 = new javax.swing.JButton();
        boton28 = new javax.swing.JButton();
        boton29 = new javax.swing.JButton();
        boton30 = new javax.swing.JButton();
        boton31 = new javax.swing.JButton();
        boton32 = new javax.swing.JButton();
        boton33 = new javax.swing.JButton();
        boton34 = new javax.swing.JButton();
        boton35 = new javax.swing.JButton();
        boton36 = new javax.swing.JButton();
        boton37 = new javax.swing.JButton();
        boton38 = new javax.swing.JButton();
        boton39 = new javax.swing.JButton();
        boton40 = new javax.swing.JButton();
        boton41 = new javax.swing.JButton();
        boton42 = new javax.swing.JButton();
        boton43 = new javax.swing.JButton();
        boton44 = new javax.swing.JButton();
        boton45 = new javax.swing.JButton();
        boton46 = new javax.swing.JButton();
        boton47 = new javax.swing.JButton();
        boton48 = new javax.swing.JButton();
        boton49 = new javax.swing.JButton();
        boton50 = new javax.swing.JButton();
        boton51 = new javax.swing.JButton();
        boton52 = new javax.swing.JButton();
        boton53 = new javax.swing.JButton();
        boton54 = new javax.swing.JButton();
        boton55 = new javax.swing.JButton();
        boton56 = new javax.swing.JButton();
        boton57 = new javax.swing.JButton();
        boton58 = new javax.swing.JButton();
        boton59 = new javax.swing.JButton();
        boton60 = new javax.swing.JButton();
        boton61 = new javax.swing.JButton();
        boton62 = new javax.swing.JButton();
        boton63 = new javax.swing.JButton();
        boton64 = new javax.swing.JButton();
        boton65 = new javax.swing.JButton();
        boton66 = new javax.swing.JButton();
        boton67 = new javax.swing.JButton();
        boton68 = new javax.swing.JButton();
        boton69 = new javax.swing.JButton();
        boton70 = new javax.swing.JButton();
        boton71 = new javax.swing.JButton();
        boton72 = new javax.swing.JButton();
        boton73 = new javax.swing.JButton();
        boton74 = new javax.swing.JButton();
        boton75 = new javax.swing.JButton();
        boton76 = new javax.swing.JButton();
        boton77 = new javax.swing.JButton();
        boton78 = new javax.swing.JButton();
        boton79 = new javax.swing.JButton();
        boton80 = new javax.swing.JButton();
        boton81 = new javax.swing.JButton();
        boton82 = new javax.swing.JButton();
        boton83 = new javax.swing.JButton();
        boton84 = new javax.swing.JButton();
        boton85 = new javax.swing.JButton();
        boton86 = new javax.swing.JButton();
        boton87 = new javax.swing.JButton();
        boton88 = new javax.swing.JButton();
        boton89 = new javax.swing.JButton();
        boton90 = new javax.swing.JButton();
        boton91 = new javax.swing.JButton();
        boton92 = new javax.swing.JButton();
        boton93 = new javax.swing.JButton();
        boton94 = new javax.swing.JButton();
        boton95 = new javax.swing.JButton();
        boton96 = new javax.swing.JButton();
        boton97 = new javax.swing.JButton();
        boton98 = new javax.swing.JButton();
        boton99 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel16 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jPanel15 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(getSize());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );

        jPanel19.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jLayeredPane5.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jPanel19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane5Layout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        TABLERO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TABLERO.add(boton01, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 810, 50, 80));
        TABLERO.add(boton00, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 810, 50, 80));
        TABLERO.add(boton02, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 810, 50, 80));
        TABLERO.add(boton04, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 810, 50, 80));
        TABLERO.add(boton03, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 810, 50, 80));
        TABLERO.add(boton05, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 810, 50, 80));
        TABLERO.add(boton06, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 810, 50, 80));
        TABLERO.add(boton07, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 810, 50, 80));
        TABLERO.add(boton08, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 810, 50, 80));
        TABLERO.add(boton09, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 810, 50, 80));
        TABLERO.add(boton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 720, 50, 80));
        TABLERO.add(boton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 720, 50, 80));
        TABLERO.add(boton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 720, 50, 80));
        TABLERO.add(boton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 720, 50, 80));
        TABLERO.add(boton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 720, 50, 80));
        TABLERO.add(boton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 720, 50, 80));
        TABLERO.add(boton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 720, 50, 80));
        TABLERO.add(boton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 720, 50, 80));
        TABLERO.add(boton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 720, 50, 80));
        TABLERO.add(boton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 720, 50, 80));
        TABLERO.add(boton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 50, 80));
        TABLERO.add(boton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 630, 50, 80));
        TABLERO.add(boton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, 50, 80));
        TABLERO.add(boton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 630, 50, 80));
        TABLERO.add(boton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 630, 50, 80));
        TABLERO.add(boton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 630, 50, 80));
        TABLERO.add(boton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 630, 50, 80));
        TABLERO.add(boton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 630, 50, 80));
        TABLERO.add(boton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 630, 50, 80));
        TABLERO.add(boton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 630, 50, 80));
        TABLERO.add(boton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 50, 80));
        TABLERO.add(boton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 50, 80));
        TABLERO.add(boton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 50, 80));
        TABLERO.add(boton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 50, 80));
        TABLERO.add(boton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 50, 80));
        TABLERO.add(boton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 50, 80));
        TABLERO.add(boton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 50, 80));
        TABLERO.add(boton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, 50, 80));
        TABLERO.add(boton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 50, 80));
        TABLERO.add(boton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 50, 80));
        TABLERO.add(boton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 50, 80));
        TABLERO.add(boton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 50, 80));
        TABLERO.add(boton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 50, 80));
        TABLERO.add(boton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 50, 80));
        TABLERO.add(boton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 50, 80));
        TABLERO.add(boton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 50, 80));
        TABLERO.add(boton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 50, 80));
        TABLERO.add(boton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 50, 80));
        TABLERO.add(boton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 50, 80));
        TABLERO.add(boton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 50, 80));
        TABLERO.add(boton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 50, 80));
        TABLERO.add(boton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 50, 80));
        TABLERO.add(boton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 50, 80));
        TABLERO.add(boton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 50, 80));
        TABLERO.add(boton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 50, 80));
        TABLERO.add(boton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 50, 80));
        TABLERO.add(boton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 50, 80));
        TABLERO.add(boton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 50, 80));
        TABLERO.add(boton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 50, 80));
        TABLERO.add(boton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 50, 80));
        TABLERO.add(boton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 50, 80));
        TABLERO.add(boton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 50, 80));
        TABLERO.add(boton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 50, 80));
        TABLERO.add(boton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 50, 80));
        TABLERO.add(boton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 50, 80));
        TABLERO.add(boton65, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 50, 80));
        TABLERO.add(boton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 50, 80));
        TABLERO.add(boton67, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 50, 80));
        TABLERO.add(boton68, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 50, 80));
        TABLERO.add(boton69, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 50, 80));
        TABLERO.add(boton70, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 50, 80));
        TABLERO.add(boton71, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 50, 80));
        TABLERO.add(boton72, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 50, 80));
        TABLERO.add(boton73, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 50, 80));
        TABLERO.add(boton74, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 50, 80));
        TABLERO.add(boton75, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 50, 80));
        TABLERO.add(boton76, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 50, 80));
        TABLERO.add(boton77, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 50, 80));
        TABLERO.add(boton78, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 50, 80));
        TABLERO.add(boton79, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 50, 80));
        TABLERO.add(boton80, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 50, 80));
        TABLERO.add(boton81, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 50, 80));
        TABLERO.add(boton82, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 50, 80));
        TABLERO.add(boton83, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 50, 80));
        TABLERO.add(boton84, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 50, 80));
        TABLERO.add(boton85, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 50, 80));
        TABLERO.add(boton86, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 50, 80));
        TABLERO.add(boton87, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 50, 80));
        TABLERO.add(boton88, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 50, 80));
        TABLERO.add(boton89, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 50, 80));
        TABLERO.add(boton90, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 50, 80));
        TABLERO.add(boton91, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 50, 80));
        TABLERO.add(boton92, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 50, 80));
        TABLERO.add(boton93, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 50, 80));
        TABLERO.add(boton94, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 50, 80));
        TABLERO.add(boton95, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 50, 80));
        TABLERO.add(boton96, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 50, 80));
        TABLERO.add(boton97, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 50, 80));
        TABLERO.add(boton98, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 50, 80));
        TABLERO.add(boton99, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 50, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\AdminColeexz\\Documents\\NetBeansProjects\\ProyectoSequence\\src\\tokens\\tableroimg.jpg")); // NOI18N
        TABLERO.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 900));

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );

        jLayeredPane2.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 1090));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );

        jLayeredPane2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 1090));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );

        jLayeredPane2.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 1090));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );

        jLayeredPane2.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 1090));

        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );

        jLayeredPane3.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 1090));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );

        jLayeredPane3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 1090));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );

        jLayeredPane3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 1090));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );

        jLayeredPane3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 1090));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TABLERO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TABLERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TABLERO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TABLERO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TABLERO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TABLERO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TABLERO().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane TABLERO;
    private javax.swing.JPanel TABLEROPANEL;
    private javax.swing.JButton boton00;
    private javax.swing.JButton boton01;
    private javax.swing.JButton boton02;
    private javax.swing.JButton boton03;
    private javax.swing.JButton boton04;
    private javax.swing.JButton boton05;
    private javax.swing.JButton boton06;
    private javax.swing.JButton boton07;
    private javax.swing.JButton boton08;
    private javax.swing.JButton boton09;
    private javax.swing.JButton boton10;
    private javax.swing.JButton boton11;
    private javax.swing.JButton boton12;
    private javax.swing.JButton boton13;
    private javax.swing.JButton boton14;
    private javax.swing.JButton boton15;
    private javax.swing.JButton boton16;
    private javax.swing.JButton boton17;
    private javax.swing.JButton boton18;
    private javax.swing.JButton boton19;
    private javax.swing.JButton boton20;
    private javax.swing.JButton boton21;
    private javax.swing.JButton boton22;
    private javax.swing.JButton boton23;
    private javax.swing.JButton boton24;
    private javax.swing.JButton boton25;
    private javax.swing.JButton boton26;
    private javax.swing.JButton boton27;
    private javax.swing.JButton boton28;
    private javax.swing.JButton boton29;
    private javax.swing.JButton boton30;
    private javax.swing.JButton boton31;
    private javax.swing.JButton boton32;
    private javax.swing.JButton boton33;
    private javax.swing.JButton boton34;
    private javax.swing.JButton boton35;
    private javax.swing.JButton boton36;
    private javax.swing.JButton boton37;
    private javax.swing.JButton boton38;
    private javax.swing.JButton boton39;
    private javax.swing.JButton boton40;
    private javax.swing.JButton boton41;
    private javax.swing.JButton boton42;
    private javax.swing.JButton boton43;
    private javax.swing.JButton boton44;
    private javax.swing.JButton boton45;
    private javax.swing.JButton boton46;
    private javax.swing.JButton boton47;
    private javax.swing.JButton boton48;
    private javax.swing.JButton boton49;
    private javax.swing.JButton boton50;
    private javax.swing.JButton boton51;
    private javax.swing.JButton boton52;
    private javax.swing.JButton boton53;
    private javax.swing.JButton boton54;
    private javax.swing.JButton boton55;
    private javax.swing.JButton boton56;
    private javax.swing.JButton boton57;
    private javax.swing.JButton boton58;
    private javax.swing.JButton boton59;
    private javax.swing.JButton boton60;
    private javax.swing.JButton boton61;
    private javax.swing.JButton boton62;
    private javax.swing.JButton boton63;
    private javax.swing.JButton boton64;
    private javax.swing.JButton boton65;
    private javax.swing.JButton boton66;
    private javax.swing.JButton boton67;
    private javax.swing.JButton boton68;
    private javax.swing.JButton boton69;
    private javax.swing.JButton boton70;
    private javax.swing.JButton boton71;
    private javax.swing.JButton boton72;
    private javax.swing.JButton boton73;
    private javax.swing.JButton boton74;
    private javax.swing.JButton boton75;
    private javax.swing.JButton boton76;
    private javax.swing.JButton boton77;
    private javax.swing.JButton boton78;
    private javax.swing.JButton boton79;
    private javax.swing.JButton boton80;
    private javax.swing.JButton boton81;
    private javax.swing.JButton boton82;
    private javax.swing.JButton boton83;
    private javax.swing.JButton boton84;
    private javax.swing.JButton boton85;
    private javax.swing.JButton boton86;
    private javax.swing.JButton boton87;
    private javax.swing.JButton boton88;
    private javax.swing.JButton boton89;
    private javax.swing.JButton boton90;
    private javax.swing.JButton boton91;
    private javax.swing.JButton boton92;
    private javax.swing.JButton boton93;
    private javax.swing.JButton boton94;
    private javax.swing.JButton boton95;
    private javax.swing.JButton boton96;
    private javax.swing.JButton boton97;
    private javax.swing.JButton boton98;
    private javax.swing.JButton boton99;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    // End of variables declaration//GEN-END:variables
}
